# Generated by Django 4.2.26 on 2025-11-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_options_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
